### ISSUE TITLE
Missing i8n

### ISSUE THREAD

**Issue by cicero200272** [balrog-kun/ha_ping_arp#1]
In device_tracker.py (line 81) the regular expression contains a hard-coded "at". 

Since the RPi where my HA installation runs is localized in German, the arp table shows "auf" instead of "at", so that the regex does not match any item at all... 

Perhaps you could use something like `[A-Za-z]+` instead of "at"?

**Comment by balrog-kun** [comment]
I'll have to check arp code but it sounds like the whole `arp -a` format can vary depending on locale, so maybe we should use the table format instead, arp with no `-a`.  But it seems that table doesn't include the IP and the hostname is trimmed to fit the column width... I'll have a look at the arp code this weekend.

**Comment by balrog-kun** [comment]
Looking at the arp code I didn't find a better solution than to use `[A-Za-z ]+` in place of the "at", both the `arp -a` and `arp -e` formats may be localized.. the latter would be better but the strings get truncated to columns widths in that format.  Thanks for the reports by the way.
